=== scarecrow3773/secure-iot-gateway/interface-partition/legacy/xml/vor-request-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Requests">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Request" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ReasonGoal" type="xs:string"/>
                            <xs:element name="Issuer" type="xs:string"/>
                            <xs:element name="Parameter" type="xs:string"/>
                            <xs:element name="Modification" type="xs:string"/>
                            <xs:element name="Description">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Item" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Impact">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Item" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Priority" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== scarecrow3773/secure-iot-gateway/interface-partition/legacy/xml/vor-request-hsel.xml
<?xml version="1.0" encoding="UTF-8"?>
<Requests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:noNamespaceSchemaLocation="vor-request-schema.xsd">
    <Request>
        <ReasonGoal>Change speed of product flow to/from highbay storage</ReasonGoal>
        <Issuer>M+O Optimizer</Issuer>
        <Parameter>DF-HB-TB1/2-CS (rel. Value [0%,100%])</Parameter>
        <Modification>Changes within parameter range</Modification>
        <Description>
            <Item>Increase of conveyor speed to remove congestion after injection molding machine</Item>
        </Description>
        <Impact>
            <Item>Remove congestion after IMM</Item>
            <Item>Increase throughput at DF-HB-TB1/2</Item>
            <Item>Increased load on highbay storage</Item>
        </Impact>
        <Priority>4</Priority>
    </Request>
    <Request>
        <ReasonGoal>Change program/operation mode of robot</ReasonGoal>
        <Issuer>M+O Optimizer, Central HMI operator</Issuer>
        <Parameter>DF-TM-DR-PR (Integer [1,32])</Parameter>
        <Modification>Changes within parameter range</Modification>
        <Description>
            <Item>Change robot program to handle different product</Item>
        </Description>
        <Impact>
            <Item>Transport station handles different product</Item>
            <Item>Gripper change necessary</Item>
        </Impact>
        <Priority>31</Priority>
    </Request>
    <Request>
        <ReasonGoal>Change operation mode of fume extraction system</ReasonGoal>
        <Issuer>M+O analytics, I4.0 device management</Issuer>
        <Parameter>DF-EM-LE-FX (Status (Boolean), Operation time)</Parameter>
        <Modification>Replacing file in memory/queue</Modification>
        <Description>
            <Item>(De)activate fume extraction system</Item>
            <Item>Change extraction cycletime</Item>
        </Description>
        <Impact>
            <Item>Reduction of air pollution</Item>
        </Impact>
        <Priority>0</Priority>
    </Request>
    <Request>
        <ReasonGoal>Upload G-Code file for next order</ReasonGoal>
        <Issuer>M+O scheduler</Issuer>
        <Parameter>DF-EM-LE-GC (G-Code file, name.gc)</Parameter>
        <Modification>Replacing file in memory/queue</Modification>
        <Description>
            <Item>Upload code for next engraving order</Item>
        </Description>
        <Impact>
            <Item>Product change</Item>
        </Impact>
        <Priority>31</Priority>
    </Request>
</Requests>
