=== scarecrow3773/secure-iot-gateway/gateway-komponenten/datenaggregation/config/modbustcp-endpoints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="modbus-servers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="server" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ipaddr" type="xs:string"/>
                            <xs:element name="port" type="xs:int"/>
                            <xs:element name="serveralias" type="xs:string"/>
                            <xs:element name="endpoints">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="endpoint" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="function" type="xs:string"/>
                                                    <xs:element name="address" type="xs:int"/>
                                                    <xs:element name="quantity" type="xs:int"/>
                                                    <xs:element name="offset" type="xs:int"/>
                                                    <xs:element name="type" type="xs:string"/>
                                                    <xs:element name="description" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== scarecrow3773/secure-iot-gateway/gateway-komponenten/datenaggregation/config/old_configs/modbustcp-endpoints_echtzeit_small.xml
<?xml version="1.0" encoding="UTF-8"?>
<modbus-servers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modbustcp-endpoints.xsd">
  <server>
    <ipaddr>192.168.200.231</ipaddr>
    <port>502</port>
    <serveralias>Workstation2</serveralias>
    <endpoints>
      <endpoint>
        <name>Piece in Position 1</name>
        <function>Read Holding Registers</function>
        <address>8001</address>
        <quantity>1</quantity>
        <offset>0</offset>
        <type>Input Registers</type>
        <description>Read Register 1 value</description>
      </endpoint>
      <endpoint>
        <name>Piece in Position 3</name>
        <function>Read Holding Registers</function>
        <address>8001</address>
        <quantity>1</quantity>
        <offset>1</offset>
        <type>Input Registers</type>
        <description>Read Register 1 value</description>
      </endpoint>
      <endpoint>
        <name>Turn drill on</name>
        <function>Write Multiple Holding Registers</function>
        <address>8003</address>
        <quantity>1</quantity>
        <offset>0</offset>
        <type>Output Registers</type>
        <description>Write Register 2 value</description>
      </endpoint>
    </endpoints>
  </server>
  
  <server>
    <ipaddr>192.168.200.230</ipaddr>
    <port>502</port>
    <serveralias>InputStation</serveralias>
    <endpoints>
      <endpoint>
        <name>Extend ejector</name>
        <function>Write Multiple Holding Registers</function>
        <address>8003</address>
        <quantity>1</quantity>
        <offset>4</offset>
        <type>Output Registers</type>
        <description>Write Register 2 value</description>
      </endpoint>
      <endpoint>
        <name>Magazine 1 empty</name>
        <function>Read Holding Registers</function>
        <address>0</address>
        <quantity>1</quantity>
        <offset>2</offset>
        <type>Input Registers</type>
        <description>Read temperature sensor values</description>
      </endpoint>
      <endpoint>
        <name>Height sensor measured piece ok</name>
        <function>Read Holding Registers</function>
        <address>0</address>
        <quantity>1</quantity>
        <offset>13</offset>
        <type>Input Registers</type>
        <description>Read humidity sensor value</description>
      </endpoint>
    </endpoints>
  </server>
</modbus-servers>
