=== scarecrow3773/secure-iot-gateway/gateway-komponenten/datenaggregation/config/opcua-endpoints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="opcua-servers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="server" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="server_app_uri" type="xs:string"/>
                            <xs:element name="client_app_uri" type="xs:string"/>
                            <xs:element name="alias" type="xs:string"/>
                            <xs:element name="security">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="policy" type="xs:string"/>
                                        <xs:element name="mode" type="xs:string"/>
                                        <xs:element name="server_certificate" type="xs:string" minOccurs="0"/>
                                        <xs:element name="client_certificate" type="xs:string" minOccurs="0"/>
                                        <xs:element name="client_private_key" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="nodes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="node" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="DisplayName" type="xs:string"/>
                                                    <xs:element name="NamespaceIndex" type="xs:int"/>
                                                    <xs:element name="IdentifierType" type="xs:string"/>
                                                    <xs:element name="Identifier" type="xs:int"/>
                                                    <xs:element name="datatype" type="xs:string"/>
                                                    <xs:element name="description" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== scarecrow3773/secure-iot-gateway/cpc-partition/config/old_configs/opcua-endpoints_factory_and_docker.xml
<?xml version="1.0" encoding="UTF-8"?>
<opcua-servers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="opcua-endpoints.xsd">
  <server>
    <server_app_uri>opc.tcp://brownfield-opcua-server:4840/freeopcua/server/</server_app_uri>
    <client_app_uri>urn:Client:foobar:docker-client</client_app_uri>
    <alias>secured-brownfield-opcua-server</alias>
    <security>
      <policy>SecurityPolicyAes256Sha256RsaPss</policy>
      <mode>SignAndEncrypt</mode>
      <server_certificate>certificates/trusted/brownfield_server_cert.der</server_certificate>
      <client_certificate>certificates/client_cert.der</client_certificate>
      <client_private_key>certificates/client_key.pem</client_private_key>
    </security>
    <nodes>
      <node>
        <DisplayName>MyObject</DisplayName>
        <NamespaceIndex>0</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>20001</Identifier>
        <datatype>Object</datatype>
        <description>Haifischfuetterung</description>
      </node>
      <node>
        <DisplayName>MyVariable</DisplayName>
        <NamespaceIndex>0</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>20002</Identifier>
        <datatype>Float</datatype>
        <description>Haifischfuetterung</description>
      </node>

      <node>
        <DisplayName>System1</DisplayName>
        <NamespaceIndex>0</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>20003</Identifier>
        <datatype>Object</datatype>
        <description>System1 object containing variables</description>
      </node>
      <node>
        <DisplayName>KeyPersonnelPresent</DisplayName>
        <NamespaceIndex>0</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>20004</Identifier>
        <datatype>Boolean</datatype>
        <description>Indicates if key personnel is present</description>
      </node>
      <node>
        <DisplayName>SystemAvailable</DisplayName>
        <NamespaceIndex>0</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>20005</Identifier>
        <datatype>Boolean</datatype>
        <description>Indicates if System1 is available</description>
      </node>
      <node>
        <DisplayName>OperationMode</DisplayName>
        <NamespaceIndex>0</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>20006</Identifier>
        <datatype>String</datatype>
        <description>Current operation mode of System1</description>
      </node>
      <node>
        <DisplayName>Warning</DisplayName>
        <NamespaceIndex>0</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>20007</Identifier>
        <datatype>String</datatype>
        <description>Warning state of System1</description>
      </node>
    </nodes>
  </server>

  <server>
    <server_app_uri>opc.tcp://brownfield-opcua-server:4841/freeopcua/server/</server_app_uri>
    <client_app_uri>urn:Client1:foobar:python-no-security</client_app_uri>
    <alias>unsecured-brownfield-opcua-server</alias>
    <security>
      <policy>SecurityPolicyNone</policy>
      <mode>None</mode>
    </security>
    <nodes>
      <node>
        <DisplayName>PieceHasBeenProduced</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>2</Identifier>
        <datatype>Boolean</datatype>
        <description>Haifischfuetterung</description>
      </node>
      <node>
        <DisplayName>Temperature</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>3</Identifier>
        <datatype>Float</datatype>
        <description>Haifischfuetterung</description>
      </node>
      <node>
        <DisplayName>ProductionStep</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>4</Identifier>
        <datatype>Float</datatype>
        <description>Hallihallo</description>
      </node>
      <node>
        <DisplayName>ModeOfOperation</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>5</Identifier>
        <datatype>String</datatype>
        <description>Hier koennte ihre Werbung stehen :D</description>
      </node>
      <node>
        <DisplayName>Object</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>1</Identifier>
        <datatype>Object</datatype>
        <description>Das hier ist ein OPC UA Objekt und sollte nicht gelesen werden.</description>
      </node>
      <node>
        <DisplayName>PieceHasBeenProduced</DisplayName>
        <NamespaceIndex>3</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>2</Identifier>
        <datatype>Boolean</datatype>
        <description>Namespace2</description>
      </node>
      <node>
        <DisplayName>Temperature</DisplayName>
        <NamespaceIndex>3</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>3</Identifier>
        <datatype>Float</datatype>
        <description>Namespace2</description>
      </node>
      <node>
        <DisplayName>ProductionStep</DisplayName>
        <NamespaceIndex>3</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>4</Identifier>
        <datatype>Float</datatype>
        <description>Namespace2</description>
      </node>
      <node>
        <DisplayName>ModeOfOperation</DisplayName>
        <NamespaceIndex>3</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>5</Identifier>
        <datatype>String</datatype>
        <description>Namespace2</description>
      </node>
      <node>
        <DisplayName>Object</DisplayName>
        <NamespaceIndex>3</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>1</Identifier>
        <datatype>Object</datatype>
        <description>Namespace2</description>
      </node>
    </nodes>
  </server>

  <server>
    <server_app_uri>opc.tcp://192.168.158.105:4840</server_app_uri>
    <client_app_uri>urn:revpi:laser-engraver</client_app_uri>
    <alias>unsecured-revpi-opcua-server</alias>
    <security>
      <policy>SecurityPolicyNone</policy>
      <mode>None</mode>
    </security>
    <nodes>
      <node>
        <DisplayName>list_of_files</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>9</Identifier>
        <datatype>String</datatype>
        <description>Names of available files</description>
      </node>
      <node>
        <DisplayName>count_done</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>15</Identifier>
        <datatype>Int64</datatype>
        <description>Number of completed tasks</description>
      </node>
      <node>
        <DisplayName>count_todo</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>14</Identifier>
        <datatype>Int64</datatype>
        <description>Number of pending tasks</description>
      </node>
      <node>
        <DisplayName>done_list</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>13</Identifier>
        <datatype>String</datatype>
        <description>List of completed items</description>
      </node>
      <node>
        <DisplayName>next_order</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>11</Identifier>
        <datatype>String</datatype>
        <description>Next task in queue</description>
      </node>
      <node>
        <DisplayName>todo_list</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>12</Identifier>
        <datatype>String</datatype>
        <description>List of pending tasks</description>
      </node>
      <node>
        <DisplayName>is_connected</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>6</Identifier>
        <datatype>Boolean</datatype>
        <description>System connection status</description>
      </node>
      <node>
        <DisplayName>is_mcu_connected</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>7</Identifier>
        <datatype>Boolean</datatype>
        <description>MCU connectivity status</description>
      </node>
      <node>
        <DisplayName>is_running</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>8</Identifier>
        <datatype>Boolean</datatype>
        <description>Is the system running</description>
      </node>
      <node>
        <DisplayName>progress</DisplayName>
        <NamespaceIndex>2</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
        <Identifier>10</Identifier>
        <datatype>Int64</datatype>
        <description>Job progress percent</description>
      </node>
    </nodes>
  </server>

  <server>
    <server_app_uri>opc.tcp://192.168.159.198:4840</server_app_uri>
    <client_app_uri>urn:s7-1200</client_app_uri>
    <alias>s7-1200-opcua-server</alias>
    <security>
      <policy>SecurityPolicyNone</policy>
      <mode>None</mode>
    </security>
    <nodes>
      <node>
        <DisplayName>availabilityKeyPersonnel</DisplayName>
        <NamespaceIndex>4</NamespaceIndex>
        <IdentifierType>Numeric</IdentifierType>
